# Generate Media Specification File From ART Reccomendations File

In [1]:
import pandas as pd
from IPython.display import display
import media_compiler as mc

In [2]:
df = pd.read_csv('data/indigoidine/indigoidine_media_Cycle1.csv')
rec_df = pd.read_csv('data/indigoidine/Cycle1_Recommendations.csv',delimiter='\t')
df.tail()
dest_df = df.loc[df['Plate']=='dest_plate'].reset_index()
dest_df = dest_df.loc[:,dest_df.columns != 'index']
dest_df.head()

,Plate,Well,Glucose,Na2HPO4,NaCl,KH2PO4,(NH4)2SO4,MgSO4,CaCl2,FeSO4,MnCl2,ZnSO4,CoCl2,CuSO4,Na2MoO4,Volume,Target
0,dest_plate,1,2.878468,31.827989,37.363225,22.908572,19.479759,0.151324,0.049135,0.010972,0.006837,0.009795,0.002959,0.000765,0.000595,1100,True
1,dest_plate,9,2.878468,31.827989,37.363225,22.908572,19.479759,0.151324,0.049135,0.010972,0.006837,0.009795,0.002959,0.000765,0.000595,1100,True
2,dest_plate,17,2.878468,31.827989,37.363225,22.908572,19.479759,0.151324,0.049135,0.010972,0.006837,0.009795,0.002959,0.000765,0.000595,1100,True
3,dest_plate,2,1.881197,29.593338,3.746539,1.420742,13.203982,1.325746,0.100210,0.002483,0.009025,0.001483,0.002718,0.000577,0.000445,1100,True
4,dest_plate,10,1.881197,29.593338,3.746539,1.420742,13.203982,1.325746,0.100210,0.002483,0.009025,0.001483,0.002718,0.000577,0.000445,1100,True

In [3]:
media_cols = [col for col in rec_df.columns if col not in ['Unnamed: 0','Indigoidine']]
rec_df = rec_df.loc[:,media_cols]

In [4]:
#Create Compatable Dataframe

for i,row in dest_df.iterrows():
    j = int(i/3)
    dest_df.loc[dest_df.index==i,media_cols] = rec_df.iloc[j].values
    
dest_df.head()
df = pd.concat([df.loc[df['Plate']!='dest_plate'],dest_df])
display(df)

,Plate,Well,Glucose,Na2HPO4,NaCl,KH2PO4,(NH4)2SO4,MgSO4,CaCl2,FeSO4,MnCl2,ZnSO4,CoCl2,CuSO4,Na2MoO4,Volume,Target
0,src_plate,1,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
1,src_plate,2,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
2,src_plate,3,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
3,src_plate,4,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
4,src_plate,5,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
5,src_plate,6,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
6,src_plate,7,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
7,src_plate,8,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
8,src_plate,9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
9,src_plate,10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
10,src_plate,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,500.000000,0.000000,0.000000,1000,False
11,src_plate,12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,250.000000,0.000000,1000,False
12,src_plate,13,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
13,src_plate,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,1000,False
14,src_plate,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,1000,False
15,src_plate,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,1000,False
16,src_plate,17,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
17,src_plate,18,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
18,src_plate,19,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
19,src_plate,20,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000,False
20,water_plate,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
21,water_plate,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
22,water_plate,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
23,water_plate,4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
24,water_plate,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
25,water_plate,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
26,water_plate,7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
27,water_plate,8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
28,water_plate,9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
29,water_plate,10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,dest_plate,6,2.519099,41.845732,31.757171,27.794466,13.720864,0.219418,0.094047,0.002622,0.008399,0.008414,0.003796,0.000087,0.000471,1100,True
16,dest_plate,14,2.519099,41.845732,31.757171,27.794466,13.720864,0.219418,0.094047,0.002622,0.008399,0.008414,0.003796,0.000087,0.000471,1100,True
17,dest_plate,22,2.519099,41.845732,31.757171,27.794466,13.720864,0.219418,0.094047,0.002622,0.008399,0.008414,0.003796,0.000087,0.000471,1100,True
18,dest_plate,7,2.909283,37.103666,7.434517,21.436033,16.273948,0.221696,0.123505,0.002588,0.008152,0.005071,0.003796,0.000087,0.000471,1100,True
19,dest_plate,15,2.909283,37.103666,7.434517,21.436033,16.273948,0.221696,0.123505,0.002588,0.008152,0.005071,0.003796,0.000087,0.000471,1100,True
20,dest_plate,23,2.909283,37.103666,7.434517,21.436033,16.273948,0.221696,0.123505,0.002588,0.008152,0.005071,0.003796,0.000087,0.000471,1100,True
21,dest_plate,8,2.933673,48.005319,16.478334,28.856334,16.169357,1.251188,0.155423,0.007168,0.007188,0.004421,0.003796,0.000087,0.000471,1100,True
22,dest_plate,16,2.933673,48.005319,16.478334,28.856334,16.169357,1.251188,0.155423,0.007168,0.007188,0.004421,0.003796,0.000087,0.000471,1100,True
23,dest_plate,24,2.933673,48.005319,16.478334,28.856334,16.169357,1.251188,0.155423,0.007168,0.007188,0.004421,0.003796,0.000087,0.000471,1100,True
24,dest_plate,25,0.305964,24.730769,42.261403,14.858628,14.047542,0.361347,0.194063,0.017843,0.009231,0.009177,0.003796,0.000087,0.000471,1100,True
25,dest_plate,33,0.305964,24.730769,42.261403,14.858628,14.047542,0.361347,0.194063,0.017843,0.009231,0.009177,0.003796,0.000087,0.000471,1100,True
26,dest_plate,41,0.305964,24.730769,42.261403,14.858628,14.047542,0.361347,0.194063,0.017843,0.009231,0.009177,0.003796,0.000087,0.000471,1100,True
27,dest_plate,26,2.872783,45.659306,40.150490,28.109278,9.992718,1.121623,0.152448,0.006913,0.006981,0.004375,0.003796,0.000087,0.000471,1100,True
28,dest_plate,34,2.872783,45.659306,40.150490,28.109278,9.992718,1.121623,0.152448,0.006913,0.006981,0.004375,0.003796,0.000087,0.000471,1100,True
29,dest_plate,42,2.872783,45.659306,40.150490,28.109278,9.992718,1.121623,0.152448,0.006913,0.006981,0.004375,0.003796,0.000087,0.000471,1100,True
30,dest_plate,27,2.867015,33.337995,25.216223,28.875187,8.908615,0.051476,0.159743,0.003630,0.004308,0.005788,0.003796,0.000087,0.000471,1100,True
31,dest_plate,35,2.867015,33.337995,25.216223,28.875187,8.908615,0.051476,0.159743,0.003630,0.004308,0.005788,0.003796,0.000087,0.000471,1100,True
32,dest_plate,43,2.867015,33.337995,25.216223,28.875187,8.908615,0.051476,0.159743,0.003630,0.004308,0.005788,0.003796,0.000087,0.000471,1100,True
33,dest_plate,28,0.385196,24.950104,40.458626,3.305948,14.116512,0.294462,0.189906,0.017620,0.009505,0.009252,0.003796,0.000087,0.000471,1100,True
34,dest_plate,36,0.385196,24.950104,40.458626,3.305948,14.116512,0.294462,0.189906,0.017620,0.009505,0.009252,0.003796,0.000087,0.000471,1100,True
35,dest_plate,44,0.385196,24.950104,40.458626,3.305948,14.116512,0.294462,0.189906,0.017620,0.009505,0.009252,0.003796,0.000087,0.000471,1100,True
36,dest_plate,29,2.691231,48.820373,17.272485,24.711970,10.602949,0.379017,0.180139,0.005008,0.003236,0.002872,0.003796,0.000087,0.000471,1100,True
37,dest_plate,37,2.691231,48.820373,17.272485,24.711970,10.602949,0.379017,0.180139,0.005008,0.003236,0.002872,0.003796,0.000087,0.000471,1100,True
38,dest_plate,45,2.691231,48.820373,17.272485,24.711970,10.602949,0.379017,0.180139,0.005008,0.003236,0.002872,0.003796,0.000087,0.000471,1100,True
39,dest_plate,30,2.523669,46.152715,11.778217,25.838343,10.025270,0.420965,0.175757,0.008769,0.005086,0.007654,0.003796,0.000087,0.000471,1100,True
40,dest_plate,38,2.523669,46.152715,11.778217,25.838343,10.025270,0.420965,0.175757,0.008769,0.005086,0.007654,0.003796,0.000087,0.000471,1100,True
41,dest_plate,46,2.523669,46.152715,11.778217,25.838343,10.025270,0.420965,0.175757,0.008769,0.005086,0.007654,0.003796,0.000087,0.000471,1100,True
42,dest_plate,31,2.582198,32.982194,14.809108,0.118519,17.886046,2.320352,0.110268,0.004178,0.001783,0.008530,0.003796,0.000087,0.000471,1100,True
43,dest_plate,39,2.582198,32.982194,14.809108,0.118519,17.886046,2.320352,0.110268,0.004178,0.001783,0.008530,0.003796,0.000087,0.000471,1100,True
44,dest_plate,47,2.582198,32.982194,14.809108,0.118519,17.886046,2.320352,0.110268,0.004178,0.001783,0.008530,0.003796,0.000087,0.000471,1100,True

In [5]:
df.to_csv('data/indigoidine/indigoidine_media_Cycle2.csv',index=False)

In [6]:
#Create Combinatorial Media
df = df.set_index(['Plate','Well'])
mc.compile_media(df)

Tips Needed By Subrutine
Adding Water To Mixing Plate (Done with 8 tips in method): 131 Tips,  2 Plates
Adding Water to Destination Plate (Done with 8 Tips): 228 Tips,  3 Plates
Diluting Stock Solutions: 38 Tips,  1 Plates
Adding Undilute Media To Dest: 216 Tips,  3 Plates
Mixing Final Media: 369 Tips,  4 Plates

Overall Experiment Need
Total Tips Needed: 982
Tip Plates Consumed: 11